<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Dish;
use App\Models\Restaurant;

class DishSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $dishes = [
            //KEBAB NOT BAD
            [
                'name'=> 'Kebab Piadina',
                'description'=> 'Piadina bella calda 2km',
                'ingredients'=> 'Impasto di piadina bella calda 2km',
                'price'=> 4.50,
                'image'=> 'https://d2j6dbq0eux0bg.cloudfront.net/images/73313140/2981172261.jpg',
                'visible'=> true,
                'restaurant_id'=> 1,
            ],
            [
                'name'=> 'Patatine fritte',
                'description'=> 'Frito belo',
                'ingredients'=> 'ti fidi di me?',
                'price'=> 2.50,
                'image'=> 'https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/03/1457008490_947a03d0316de9c5ec47c435911c5c0d64c0a495-1430067252.jpg?w=580',
                'visible'=> true,
                'restaurant_id'=> 1,
            ],
            [
                'name'=> 'Kebab panino',
                'description'=> 'Kebab panino calda 2km',
                'ingredients'=> 'Impasto di panino bella calda 2km',
                'price'=> 3.50,
                'image'=> 'https://d2j6dbq0eux0bg.cloudfront.net/images/62400814/2367230254.jpg',
                'visible'=> true,
                'restaurant_id'=> 1,
            ],
            [
                'name'=> 'Menu kebab panino',
                'description'=> 'Panino kebab + patatine + bibita',
                'ingredients'=> 'Panino, patatine',
                'price'=> 7.50,
                'image'=> 'http://kappa2kebab.com/wp-content/uploads/2020/09/m1.jpg',
                'visible'=> true,
                'restaurant_id'=> 1,
            ],
            [
                'name'=> 'Menu kebab piadina',
                'description'=> 'Panino kebab + patatine + bibita',
                'ingredients'=> 'Panino, patatine',
                'price'=> 8.50,
                'image'=> 'https://inconsegna.com/wp-content/uploads/2020/10/menu-piadina.jpg',
                'visible'=> true,
                'restaurant_id'=> 1,
            ],
            //PIZZA PALACE
            [
                'name'=> 'Pizza Margherita',
                'description'=> 'Tipica margheritina per la principessa',
                'ingredients'=> 'Pomodoro, Mozzarella',
                'price'=> 4.50,
                'image'=> 'https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800/public/fdl_content_import_it/margherita-50kalo.jpg.webp?itok=QlO8_AHv',
                'visible'=> true,
                'restaurant_id'=> 2,
            ],
            [
                'name'=> 'Diavola',
                'description'=> 'Pronto per bruciare tra le fiamme? ti abbraccia il piccante del diavolo',
                'ingredients'=> 'Pomodoro, Mozzarella, Salame piccante con grana',
                'price'=> 6.50,
                'image'=> 'https://i1.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/06/3236_Pizza.jpg?resize=895%2C616&ssl=1',
                'visible'=> true,
                'restaurant_id'=> 2,
            ],
            [
                'name'=> 'Prosciutto e funghi',
                'description'=> 'Siamo in campagna con qualche oink oink e un funghetto che spunta dietro di te!',
                'ingredients'=> 'Pomodoro, Mozzarella, Prosciutto cotto e funghi',
                'price'=> 7,
                'image'=> 'https://www.pizzeriasenzatempo.it/wp-content/uploads/2020/04/PROSCIUTTO-E-FUNGHI.jpg',
                'visible'=> true,
                'restaurant_id'=> 2,
            ],
            [
                'name'=> 'Capricciosa',
                'description'=> 'Una pizza leggermente capricciosa!',
                'ingredients'=> 'Pomodoro, mozzarella, prosciutto, funghi, carciofi e olive',
                'price'=> 7.50,
                'image'=> 'https://wips.plug.it/cips/buonissimo.org/cms/2019/09/pizza-capricciosa.jpg',
                'visible'=> true,
                'restaurant_id'=> 2,
            ],
            [
                'name'=> 'Mantovana',
                'description'=> 'Da mantova!',
                'ingredients'=> 'Pomodoro, Mozzarella, Salsiccia, Parmigiano',
                'price'=> 6.50,
                'image'=> 'https://1.bp.blogspot.com/-g-dHqMIl5EU/XYMsT21m83I/AAAAAAAAVfk/2IhuAk38O307IEMxhPREjli7r_svZ9vDwCEwYBhgL/s1600/pizza%2Bmantovana2.jpg',
                'visible'=> true,
                'restaurant_id'=> 2,
            ],
            //SUSHI YA!
            [
                'name'=> 'Riso cantonese',
                'description'=> '',
                'ingredients'=> 'Riso, piselli, speck, uova',
                'price'=> 5,
                'image'=> 'https://www.giallozafferano.it/images/229-22992/Riso-alla-cantonese_450x300.jpg',
                'visible'=> true,
                'restaurant_id'=> 3,
            ],
            [
                'name'=> 'Uramaki Ebiten',
                'description'=> "Un gamberetto tuffatosi nell'olio fritto e caldo bollente che ribolle mlml",
                'ingredients'=> 'Riso, gambero fritto, alga nori',
                'price'=> 9,
                'image'=> 'https://www.deabyday.tv/.imaging/default/article/guides/cucina-e-ricette/primi/Uramaki-ebiten--la-ricetta-originale-giapponese/imageOriginal.jpg',
                'visible'=> true,
                'restaurant_id'=> 3,
            ],
            [
                'name'=> 'Sashimi al salmone',
                'description'=> '',
                'ingredients'=> 'Riso e salmone',
                'price'=> 3,
                'image'=> 'https://primochef.it/wp-content/uploads/2021/11/SH_sashimi_di_salmone.jpg',
                'visible'=> true,
                'restaurant_id'=> 3,
            ],
            [
                'name'=> 'Wakame salad',
                'description'=> 'Insalata di alghe',
                'ingredients'=> 'Alghe',
                'price'=> 6.50,
                'image'=> 'https://www.saporiko.it/wp-content/uploads/2020/05/Goma-wakame-saporiko-vittuone-1.jpg',
                'visible'=> true,
                'restaurant_id'=> 3,
            ],
            // BURGER BUSTERS
            [
                'name'=> 'Massachusetts burger',
                'description'=> 'Doppio cheddar,doppio bacon, doppio formaggio, insalata e piccante',
                'ingredients'=> 'pane, hamburger, cheddar, bacon, formaggio, insalata, salsa piccante',
                'price'=> 10.50,
                'image'=> 'https://bigseventravel.com/wp-content/uploads/2019/12/tico-1.jpg',
                'visible'=> true,
                'restaurant_id'=> 4,
            ],
            [
                'name'=> 'Coca Cola',
                'description'=> 'Coca Cola',
                'ingredients'=> 'Acqua, anidride carbonica, zucchero, colorante caramello (E 150D), aromi naturali, caffeina e acido fosforico',
                'price'=> 2.50,
                'image'=> 'https://spesaonline.conad.it/assets/products/coca-cola-original-taste-pet-1-l--10890749/ID-Shot.jpeg/renditions/cq5dam.web.1280.1280.jpeg',
                'visible'=> true,
                'restaurant_id'=> 4,
            ],
            [
                'name'=> 'Onion rings',
                'description'=> 'Anelli di cipolla pastellati e fritti, serviti con salsa barbecue',
                'ingredients'=> 'Cipolle, farina, lievito istantaneo, uova, latte intero, olio',
                'price'=> 10.50,
                'image'=> 'https://thecozycook.com/wp-content/uploads/2020/07/Onion-Rings-Recipe-f.jpg',
                'visible'=> true,
                'restaurant_id'=> 4,
            ],
            [
                'name'=> 'Chicken wings',
                'description'=> 'Ali di pollo fritte con erba cipollina, ricoperte con salsa buffalo piccante e salsa blue cheese',
                'ingredients'=> 'pollo, erba cipollina, salsa buffalo',
                'price'=> 8.50,
                'image'=> 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/delish-220129-apricot-chicken-wings-003-ab-web-1647621955.jpg',
                'visible'=> true,
                'restaurant_id'=> 4,
            ],
            [
                'name'=> 'Pulled pork bites',
                'description'=> 'Bocconcini di pulled pork fritti, accompagnati dalla nostra salsa barbecue',
                'ingredients'=> 'maiale, salsa bbq',
                'price'=> 9.50,
                'image'=> 'https://www.salomon-foodworld.com/media/pages/sortiment/pulled-pork-bites/6a0a9ba755-1676654740/pulled-pork-bites-rezept-72dpi-e3-800x.jpg',
                'visible'=> true,
                'restaurant_id'=> 4,
            ],
            [
                'name'=> 'Egg bacon cheeseburger',
                'description'=> 'Manzo sceltissimo 200gr ricetta home made, pomodoro, lattuga, cheddar, cetriolo agrodolce, crispy bacon, uovo al tegamino e salsa burger',
                'ingredients'=> 'manzo, pomodoro, lattuga, cheddar, cetriolo, bacon, uovo, salsa burger',
                'price'=> 12.50,
                'image'=> 'https://www.lifeasastrawberry.com/wp-content/uploads/2017/06/loaded-bacon-cheeseburger-9s.jpg',
                'visible'=> true,
                'restaurant_id'=> 4,
            ],
            // RISTORANTE CINESE MING:
            [
                'name'=> 'Sake don',
                'description'=> 'Riso ricoperto di salmone crudo',
                'ingredients'=> 'riso, salmone, salsa teriyaki',
                'price'=> 7.00,
                'image'=> 'https://i0.wp.com/unfussyepicure.com/wp-content/uploads/2015/04/sake-don-1.jpg?fit=1200%2C900&ssl=1',
                'visible'=> true,
                'restaurant_id'=> 5,
            ],
            [
                'name'=> 'Spaghetti con pollo',
                'description'=> 'Pollo, verdure e uova',
                'ingredients'=> 'spaghetti, pollo, verdure, uova',
                'price'=> 8.00,
                'image'=> 'https://www.basilicosecco.com/wp-content/uploads/2021/11/spaghetti-riso-2.jpg',
                'visible'=> true,
                'restaurant_id'=> 5,
            ],
            [
                'name'=> 'Pollo alle mandorle',
                'description'=> 'Mandorle e bambù',
                'ingredients'=> 'pollo, mandorle, bambù',
                'price'=> 5.50,
                'image'=> 'https://www.ricetteperbimby.it/foto-ricette/pollo-alle-mandorle-bimby.jpg',
                'visible'=> true,
                'restaurant_id'=> 5,
            ],
            [
                'name'=> 'Anatra con arancia',
                'description'=> '',
                'ingredients'=> 'anatra, arancia',
                'price'=> 6.50,
                'image'=> 'https://www.ricettasprint.it/wp-content/uploads/2019/12/Anatra-allarancia.jpg',
                'visible'=> true,
                'restaurant_id'=> 5,
            ],
            [
                'name'=> 'Maiale con funghi e bambù',
                'description'=> 'funghi e bambù',
                'ingredients'=> 'manzo, funghi, bambù',
                'price'=> 7.50,
                'image'=> 'https://admin.leggimenu.it/uploads/voci/75rkdfal81p1/151498215261dc7f4f4947d0.70870726.jpg',
                'visible'=> true,
                'restaurant_id'=> 5,
            ],
            [
                'name'=> 'Gamberi al curry',
                'description'=> '',
                'ingredients'=> 'gamberi, curry, cipolla e bambù',
                'price'=> 5.50,
                'image'=> 'https://www.mangiaconme.it/wp-content/uploads/2017/07/Kaeng_Kari_Kung_177_risultato.jpg',
                'visible'=> true,
                'restaurant_id'=> 5,
            ],
            // TAJ MAHAL:
            [
                'name'=> 'Vegetable Biryani',
                'description'=> 'Riso basmati speziato saltato in padella con zucchine, carote e piselli',
                'ingredients'=> 'riso, zucchine, carote, piselli',
                'price'=> 5.50,
                'image'=> 'https://img.taste.com.au/_L7m5vxs/taste/2016/11/vegetable-biryani-102620-1.jpeg',
                'visible'=> true,
                'restaurant_id'=> 6,
            ],
            [
                'name'=> 'Samosa alla Carne (2pz)',
                'description'=> 'Fagottino ripieno di carne di pollo macinato',
                'ingredients'=> 'pollo macinato',
                'price'=> 4.50,
                'image'=> 'https://wips.plug.it/cips/buonissimo.org/cms/2020/10/samosa.jpg?w=713&a=c&h=407',
                'visible'=> true,
                'restaurant_id'=> 6,
            ],
            [
                'name'=> 'Chicken Tikka Masala',
                'description'=> 'Pollo alla griglia marinato in salsa da coriandolo fresco, zenzero, aglio, cipolla e spezie',
                'ingredients'=> 'Pollo, salsa di coriandolo, zenzero, aglio, cipolla, spezie',
                'price'=> 12.50,
                'image'=> 'https://wips.plug.it/cips/buonissimo.org/cms/2020/10/samosa.jpg?w=713&a=c&h=407',
                'visible'=> true,
                'restaurant_id'=> 6,
            ],
            [
                'name'=> 'Tandoori Chicken',
                'description'=> 'Metà pollo alla griglia marinato per 24 ore in yogurt speziato e cotto alla piastra',
                'ingredients'=> 'Pollo, yogurt speziato',
                'price'=> 9.50,
                'image'=> 'https://images.getrecipekit.com/20220914002000-tandoori-murgh-533x800-d63b989b-7768-489a-bbb6-bd9e4dfc10f5.jpg?aspect_ratio=1:1&quality=90&',
                'visible'=> true,
                'restaurant_id'=> 6,
            ],
            [
                'name'=> 'Muglai Paratha',
                'description'=> 'Pane fritto con uova, cipolla, cumino, coriandolo, peperoncino verde',
                'ingredients'=> 'Pane, uova, cipolla, cumino, coriandolo, peperoncino verde',
                'price'=> 7.00,
                'image'=> 'https://foodalltime.com/wp-content/uploads/2018/06/A-healthy-breakfast-2.jpg',
                'visible'=> true,
                'restaurant_id'=> 6,
            ],
            [
                'name'=> 'Jali Kabab (4pz)',
                'description'=> 'Polpette di carne macinata con cipolla, menta, spezie',
                'ingredients'=> 'Carne macinata, cipolla, menta, spezie',
                'price'=> 9.50,
                'image'=> 'https://i.ytimg.com/vi/P1nOYxwqKVk/maxresdefault.jpg',
                'visible'=> true,
                'restaurant_id'=> 6,
            ],
            // TAVERNA GRECA:
            [
                'name'=> 'Pita Special',
                'description'=> 'gyros di pollo patatine fritte rustiche ketchup, senape.',
                'ingredients'=> 'pollo, patatine fritte, ketchup, senape .',
                'price'=> 6.50,
                'image'=> 'https://media.istockphoto.com/id/1017035608/it/foto/pita-di-gyros-greco-con-carne-tritata-patatine-fritte-pomodori-e-salsa-tzatziki.jpg?s=170667a&w=0&k=20&c=rbcsxnl48pKeVflWtzuDJzznHoelGFpqTmaLsC_PuOI=',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Baklava',
                'description'=> 'Pasta fillo greca, ricoperta con sciroppo al miele e noci',
                'ingredients'=> 'Pasta fillo greca, sciroppo al miele, noci',
                'price'=> 4.50,
                'image'=> 'https://www.allrecipes.com/thmb/lKh_tDDLRgfZeyTTl9E6_H2S284=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/9454-Greek-Baklava-mfs-197-4x3-3b5e54cd63714cb8a4b80715a95cd5b9.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Spanakopita',
                'description'=> 'Pasta fillo greca, farcita con formaggio greco feta e spinaci',
                'ingredients'=> 'Pasta fillo greca, formaggio greco, feta, spinaci',
                'price'=> 5.90,
                'image'=> 'https://www.thespruceeats.com/thmb/2Fk-NEscVoBNWDuzbiQw-LyS-QQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/spinach-pie-with-feta-spanakopita-1706022_hero-01-80cc6ee388474e7aad68e1d009766967.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Tyropita',
                'description'=> 'Pasta fillo greca, farcita con formaggio greco feta',
                'ingredients'=> 'Pasta fillo greca, farcita con formaggio greco feta',
                'price'=> 5.90,
                'image'=> 'https://fillofactory.com/wp-content/uploads/2023/01/thumbnail_Feta-cheese-filo-triangles-800x530.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Jali Kabab (4pz)',
                'description'=> 'Polpette di carne macinata con cipolla, menta, spezie',
                'ingredients'=> 'Carne macinata, cipolla, menta, spezie',
                'price'=> 9.50,
                'image'=> 'https://i.ytimg.com/vi/P1nOYxwqKVk/maxresdefault.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Pita souvlaki',
                'description'=> 'Carne di suino, insalata, pomodori, cipolla e salsa tzatziki',
                'ingredients'=> 'Carne di suino, insalata, pomodori, cipolla, salsa tzatziki',
                'price'=> 6.50,
                'image'=> 'https://www.advisato.it/blog/wp-content/uploads/2017/09/gyros.jpg',
                'visible'=> true,
                'restaurant_id'=> 7,
            ],
            // LA PIAZZETTA:
            [
                'name'=> 'Cacio e pepe',
                'description'=> 'Pecorino romano e pepe',
                'ingredients'=> 'Pecorino romano, pepe',
                'price'=> 9.50,
                'image'=> 'https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2021/01/Pasta-cacio-e-pepe-2634.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Amatriciana',
                'description'=> 'Pomodoro, guanciale e pecorino romano',
                'ingredients'=> 'Pomodoro, guanciale e pecorino romano',
                'price'=> 10.50,
                'image'=> 'https://blog.giallozafferano.it/allacciateilgrembiule/wp-content/uploads/2020/02/bucatini-all-amatriciana.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Carbonara',
                'description'=> 'Uova, guanciale, pecorino romano e pepe',
                'ingredients'=> 'Uova, guanciale, pecorino romano e pepe',
                'price'=> 10.50,
                'image'=> 'https://blog.giallozafferano.it/dulcisinforno/wp-content/uploads/2021/03/Carbonara-ricetta-5328.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Trofie al pesto',
                'description'=> 'basilico, parmigiano, olio, pinoli',
                'ingredients'=> 'basilico, parmigiano, olio, pinoli',
                'price'=> 8.50,
                'image'=> 'https://www.todis.it/wp-content/uploads/2021/09/5-varianti-per-preparare-la-pasta-al-pesto.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Fettuccine crema di broccolo siciliano',
                'description'=> 'Mollica di pane tostata e maggiorana',
                'ingredients'=> 'Mollica di pane tostata e maggiorana',
                'price'=> 9.50,
                'image'=> 'https://www.ilcuoreinpentola.it/wp-content/uploads/2018/02/pasta-e-broccoli-alla-siciliana.jpeg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            [
                'name'=> 'Tonnarello salsa di cozze',
                'description'=> 'Cozze e sedano candito',
                'ingredients'=> 'Cozze e sedano candito',
                'price'=> 11.50,
                'image'=> 'https://www.pastarmando.it/images/ricette/_large/1502143080737_170828_115251.jpg',
                'visible'=> true,
                'restaurant_id'=> 8,
            ],
            // PIZZA HOUSE:
            [
                'name'=> 'Pizza Cacio e pepe',
                'description'=> 'Mozzarella, fiordilatte, pecorino, pepe',
                'ingredients'=> 'Mozzarella, fiordilatte, pecorino, pepe',
                'price'=> 9.50,
                'image'=> 'https://www.finedininglovers.com/sites/g/files/xknfdk626/files/styles/recipes_1200_800_fallback/public/2022-06/cacio_pepe_pizza_pizzana_daniele_uditi.jpg?itok=Lqkthtnw',
                'visible'=> true,
                'restaurant_id'=> 9,
            ],
            [
                'name'=> 'Pizza Patate e salsiccia',
                'description'=> 'Mozzarella, fiordilatte, patate e salsiccia',
                'ingredients'=> 'Mozzarella, fiordilatte, patate e salsiccia',
                'price'=> 10.50,
                'image'=> 'https://shop.eismann.it/upload/product-detail-theme/it/33162-pizza-suprema-salsiccia-e-patate-K-20220303.jpg',
                'visible'=> true,
                'restaurant_id'=> 9,
            ],
            [
                'name'=> 'Pizza Speck e stracchino',
                'description'=> 'Mozzarella, fiordilatte, speck, stracchino, pachino e basilico',
                'ingredients'=> 'Mozzarella, fiordilatte, speck, stracchino, pachino e basilico',
                'price'=> 10.50,
                'image'=> 'pizza_stracchino_pomodorini_e_speck_3.avif',
                'visible'=> true,
                'restaurant_id'=> 9,
            ],
            [
                'name'=> 'Pizza Bresaola, rucola e grana',
                'description'=> 'Mozzarella, fiordilatte, bresaola, rucola e grana',
                'ingredients'=> 'Mozzarella, fiordilatte, bresaola, rucola e grana',
                'price'=> 8.90,
                'image'=> 'https://www.mondopizzaudine.com/utenti/bledar_it/cache/_pics/4/3/img-6588_d63d66d9c87e777e830dce8812033ea9_t.webp',
                'visible'=> true,
                'restaurant_id'=> 9,
            ],
            [
                'name'=> 'Pizza Zucchine',
                'description'=> 'Mozzarella, fiordilatte e zucchine',
                'ingredients'=> 'Mozzarella, fiordilatte e zucchine',
                'price'=> 8.90,
                'image'=> 'https://www.cuocicuoci.com/wp-content/uploads/2021/06/zucchine-a-velo.jpg',
                'visible'=> true,
                'restaurant_id'=> 9,
            ],
            [
                'name'=> 'Pizza Fiori di zucca e alici',
                'description'=> 'Fiori di zucca e alici',
                'ingredients'=> 'Fiori di zucca e alici',
                'price'=> 11.50,
                'image'=> 'https://www.ricettedalmondo.it/images/foto-ricette/p/31389-pizza-con-fiori-di-zucca-e-alici.jpg',
                'visible'=> true,
                'restaurant_id'=> 9,
            ],
            // PIZZERIA GIGI:
            [
                'name'=> 'Pizza La Nerano',
                'description'=> 'Zucchine alla scapece, fiordilatte, cialda di provolone e basilico',
                'ingredients'=> 'Zucchine alla scapece, fiordilatte, cialda di provolone e basilico',
                'price'=> 10.50,
                'image'=> 'https://amalfinotizie.it/wp-content/uploads/2019/01/Pizza-alla-Nerano-Ricetta.jpg',
                'visible'=> true,
                'restaurant_id'=> 10,
            ],
            [
                'name'=> 'Pizza Würstel',
                'description'=> 'Würstel, patatine fritte, provola affumicata, cheddar e basilico',
                'ingredients'=> 'Würstel, patatine fritte, provola affumicata, cheddar e basilico',
                'price'=> 9.50,
                'image'=> 'http://www.scattidigusto.it/wp-content/uploads/2015/11/pizza-wurstel-con-patatine.jpg',
                'visible'=> true,
                'restaurant_id'=> 10,
            ],
            [
                'name'=> 'Pizza La nuova Capri',
                'description'=> 'Focaccia con datterino giallo, datterino rosso, burrata, basilico e ricotta salata',
                'ingredients'=> 'Focaccia con datterino giallo, datterino rosso, burrata, basilico e ricotta salata',
                'price'=> 11.50,
                'image'=> 'https://www.ditestaedigola.com/wp-content/uploads/2016/10/Giallo-e-Rosso.jpg',
                'visible'=> true,
                'restaurant_id'=> 10,
            ],
            [
                'name'=> 'Pizza Capricciosa',
                'description'=> 'Passata di pomodoro, fiordilatte, olive nere di Gaeta, prosciutto cotto, carciofi, funghi freschi e basilico',
                'ingredients'=> 'Passata di pomodoro, fiordilatte, olive nere di Gaeta, prosciutto cotto, carciofi, funghi freschi e basilico',
                'price'=> 11.50,
                'image'=> 'https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/12/3240_Pizza.jpg?resize=895%2C616&ssl=1',
                'visible'=> true,
                'restaurant_id'=> 10,
            ],
            [
                'name'=> 'Pizza 5 formaggi',
                'description'=> 'Gorgonzola, mozzarella, provola, cialda di grana',
                'ingredients'=> 'Gorgonzola, mozzarella, provola, cialda di grana',
                'price'=> 11.50,
                'image'=> 'https://www.ginos.pt/sites/default/files/styles/optimize/public/products/5-formaggi.jpg?itok=E2kqxAqC',
                'visible'=> true,
                'restaurant_id'=> 10,
            ],
            [
                'name'=> 'Pizza Salmone e rucola',
                'description'=> 'salmone, rucola',
                'ingredients'=> 'salmone, rucola',
                'price'=> 11.50,
                'image'=> 'https://www.silviocicchi.com/pizzachef/wp-content/uploads/2016/10/salmone-e-rucola.jpg',
                'visible'=> true,
                'restaurant_id'=> 10,
            ],
            // PIZZA ITALIA
            [
                'name'=> 'Pizza Salmone e rucola',
                'description'=> 'salmone, rucola',
                'ingredients'=> 'salmone, rucola',
                'price'=> 11.50,
                'image'=> 'https://www.silviocicchi.com/pizzachef/wp-content/uploads/2016/10/salmone-e-rucola.jpg',
                'visible'=> true,
                'restaurant_id'=> 11,
            ],
            [
                'name'=> 'Pizza La nuova Capri',
                'description'=> 'Focaccia con datterino giallo, datterino rosso, burrata, basilico e ricotta salata',
                'ingredients'=> 'Focaccia con datterino giallo, datterino rosso, burrata, basilico e ricotta salata',
                'price'=> 11.50,
                'image'=> 'https://www.ditestaedigola.com/wp-content/uploads/2016/10/Giallo-e-Rosso.jpg',
                'visible'=> true,
                'restaurant_id'=> 11,
            ],
            [
                'name'=> 'Focaccia',
                'description'=> 'focaccia bianca, rosmarino',
                'ingredients'=> 'farina, acqua, sale, olio, rosmarino',
                'price'=> 5.50,
                'image'=> 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/626FD06E-3ED3-4ED9-9726-3DB22CE53632/Derivates/D337319B-2A49-4C1C-814A-51DEA1C26E72.jpg',
                'visible'=> true,
                'restaurant_id'=> 11,
            ],
            [
                'name'=> 'Pizza Margherita',
                'description'=> 'Passata di pomodoro, fiordilatte, basilico e olio evo',
                'ingredients'=> 'Passata di pomodoro, fiordilatte, basilico e olio evo',
                'price'=> 8.50,
                'image'=> 'https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/margherita-50kalo.jpg?itok=v9nHxNMS',
                'visible'=> true,
                'restaurant_id'=> 11,
            ],
            [
                'name'=> 'Pizza Mortadella',
                'description'=> 'Mortadella, mozzarella e pistacchi e basilico',
                'ingredients'=> 'Mortadella, mozzarella e pistacchi e basilico',
                'price'=> 9.50,
                'image'=> 'https://mortadellabologna.com/wp-content/uploads/2021/09/pizza-mortadella-pistacchio-copertina.jpg',
                'visible'=> true,
                'restaurant_id'=> 11,
            ],
            [
                'name'=> 'Pizza Marinara',
                'description'=> 'Passata di pomodoro, origano, basilico, aglio e olio evo',
                'ingredients'=> 'Passata di pomodoro, origano, basilico, aglio e olio evo',
                'price'=> 6.50,
                'image'=> 'https://www.guardini.com/images/guardinispa/ricette/full/pizza-marinara.jpg',
                'visible'=> true,
                'restaurant_id'=> 11,
            ],
            // PIZZA EXPRESS:
            [
                'name'=> 'Pizza Diavola',
                'description'=> 'Mozzarella di fior di latte con pomodoro san marzano dop e salame piccante',
                'ingredients'=> 'Mozzarella di fior di latte con pomodoro san marzano dop e salame piccante',
                'price'=> 8.50,
                'image'=> 'https://i1.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/06/3236_Pizza.jpg?resize=895%2C616&ssl=1',
                'visible'=> true,
                'restaurant_id'=> 12,
            ],
            [
                'name'=> 'Pizza Vegetariana',
                'description'=> 'Melanzane, pachino, zucchine, mozzarella',
                'ingredients'=> 'Melanzane, pachino, zucchine, mozzarella',
                'price'=> 7.50,
                'image'=> 'https://www.infinitopizzeria.it/wp-content/uploads/2015/12/IMG_9237_1_92.jpg',
                'visible'=> true,
                'restaurant_id'=> 12,
            ],
            [
                'name'=> 'Birra Menabrea',
                'description'=> 'Birra Menabrea 66cl',
                'ingredients'=> 'Birra Menabrea 66cl',
                'price'=> 5.50,
                'image'=> 'https://i.ebayimg.com/images/g/DYsAAOSwpP9Y7RfI/s-l1600.jpg',
                'visible'=> true,
                'restaurant_id'=> 12,
            ],
            [
                'name'=> 'Birra Messina',
                'description'=> 'Birra della sicilia con cristalli di sale da mezzo litro',
                'ingredients'=> 'Birra della sicilia con cristalli di sale da mezzo litro',
                'price'=> 5.00,
                'image'=> 'https://gecoshop.com/4184-large_default/birra-messina-ricetta-speciale-cristalli-di-sale-cassa-24-x-33-cl.jpg',
                'visible'=> true,
                'restaurant_id'=> 12,
            ],
            // LA MARGHERITA
            [
                'name'=> 'Supplì',
                'description'=> 'Supplì',
                'ingredients'=> 'Supplì',
                'price'=> 2.00,
                'image'=> 'https://citynews-romatoday.stgy.ovh/~media/original-hi/36223387675235/suppli-7.jpg',
                'visible'=> true,
                'restaurant_id'=> 13,
            ],
            [
                'name'=> 'Birra Messina',
                'description'=> 'Birra della sicilia con cristalli di sale da mezzo litro',
                'ingredients'=> 'Birra della sicilia con cristalli di sale da mezzo litro',
                'price'=> 5.00,
                'image'=> 'https://gecoshop.com/4184-large_default/birra-messina-ricetta-speciale-cristalli-di-sale-cassa-24-x-33-cl.jpg',
                'visible'=> true,
                'restaurant_id'=> 13,
            ],
            [
                'name'=> 'Supplì Carbonara',
                'description'=> 'Supplì carbonara',
                'ingredients'=> 'Guanciale, pasta, uovo, e altro',
                'price'=> 2.50,
                'image'=> 'https://images2.corriereobjects.it/methode_image/socialshare/2022/04/06/9db368f8-b5b8-11ec-86e5-9f58259fdcbf.jpg',
                'visible'=> true,
                'restaurant_id'=> 13,
            ],
            [
                'name'=> 'Pizza Würstel',
                'description'=> 'Würstel, patatine fritte, provola affumicata, cheddar e basilico',
                'ingredients'=> 'Würstel, patatine fritte, provola affumicata, cheddar e basilico',
                'price'=> 9.50,
                'image'=> 'http://www.scattidigusto.it/wp-content/uploads/2015/11/pizza-wurstel-con-patatine.jpg',
                'visible'=> true,
                'restaurant_id'=> 13,
            ],
        ];
        
        foreach ($dishes as $dish) {
            $dish = Dish::create($dish);
        }
    }
}
